const quotes = [
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
    { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
    { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { quote: "Keep smiling, because life is a beautiful thing and there’s so much to smile about.", author: "Marilyn Monroe" },
    { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { quote: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
    { quote: "We do not remember days, we remember moments.", author: "Cesare Pavese" },
    { quote: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard" },
    { quote: "The mind is everything. What you think you become.", author: "Buddha" },
    { quote: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "Live in the sunshine, swim the sea, drink the wild air.", author: "Ralph Waldo Emerson" },
    { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { quote: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
    { quote: "Love the life you live. Live the life you love.", author: "Bob Marley" },
    { quote: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
    { quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { quote: "Life is made of ever so many partings welded together.", author: "Charles Dickens" },
    { quote: "Life is ours to be spent, not to be saved.", author: "D. H. Lawrence" },
    { quote: "The purpose of art is washing the dust of daily life off our souls.", author: "Pablo Picasso" },
    { quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
    { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { quote: "I have learned over the years that when one’s mind is made up, this diminishes fear.", author: "Rosa Parks" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "If you want to fly, you have to give up the things that weigh you down.", author: "Toni Morrison" },
    { quote: "Courage is grace under pressure.", author: "Ernest Hemingway" },
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "What we think, we become.", author: "Buddha" },
    { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" }
];


function generateQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById('quote').textContent = quotes[randomIndex].quote;
    document.getElementById('author').textContent = `- ${quotes[randomIndex].author}`;
}
